### ISSUE TITLE
Ctrl + S Issue

### ISSUE THREAD

**Issue by arthurlacoste** [vesparny/marky#9]
Version: last master compiled - Windows 10

On a new file, when you try to do a `Ctrl + S` on a new file (not already saved), you have this message:

![issue-marky](https://user-images.githubusercontent.com/13712263/32488950-b65ae6e8-c3ae-11e7-8202-ecbf3bd29ee7.png)

**Comment by vesparny** [comment]
interesting, I am not a windows user so I cannot reproduce it.
I'd be happy to accept a PR fixing this.

**Comment by arthurlacoste** [comment]
I check this to find a workaround.

I'm not a Windows user too, but I work on my Electron app Windows compatibility today.

Ok, I've found why, `dialog.showSaveDialog()` options [are no optionals](https://github.com/electron/electron/blob/master/docs/api/dialog.md#dialogshowsavedialogbrowserwindow-options-callback). I Make a PR.
